apiVersion: apps/v1
kind: Deployment
metadata:
  name: eb-flare-deployment
  labels:
    app: eb-flare-app
    type: front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eb-flare-app
      type: front-end
  template:
    metadata:
      labels:
        app: eb-flare-app
        type: front-end
    spec:
      containers:
        - name: eb-flare-container
          image: meikel19/eb-flare-test:latest
          imagePullPolicy : Always

---

apiVersion: v1
kind: Service
metadata:
  name: eb-flare-service
spec:
  type: NodePort
  selector:
    app: eb-flare-app
    type: front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30069
